import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import ExpandCircleDownIcon from '@mui/icons-material/ExpandCircleDown';

import { WelcomeDescriptionContent, WelcomeDescriptionHeader, WelcomeGoDownButton, WelcomeHeader, WelcomePageSegment, WelcomeShortDescriptionWrapper } from 'styled/components/welcome/welcome'
import styles from '../styles/Home.module.css'

export default function Home() {

  const scrollButtonRef = React.createRef<HTMLButtonElement>();

  const scrollToNextSection = () => window.scrollBy(0, 90 * (window.innerHeight / 100));

  return (
    <div>
      <Head>
        <title>Simon G. Kupisz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WelcomePageSegment className="block-center">
        <WelcomeHeader className="block-center" layout initial={{
            marginLeft: "100%",
          }} animate={{
            marginLeft: ["100%", "0%"]
          }} transition={{
            duration: 0.7,
            delay: 0.2
          }}>
            Welcome, my friend...
          </WelcomeHeader>
          <WelcomeShortDescriptionWrapper className="block-center" layout initial={{
            marginLeft: "-100%",
          }} animate={{
            marginLeft: ["-100%", "5%"]
          }} transition={{
            duration: 0.5,
            delay: 0.4
          }}>
            To the short and brief story of my career, of my skills, of who I am...
          </WelcomeShortDescriptionWrapper>
          <WelcomeGoDownButton type="button" className="block-center" layout initial={{
            scale: "0"
          }} animate={{
            scale: ["0","1"]
          }} transition={{
            duration: 0.4,
            delay: 0.9
          }} ref={scrollButtonRef}
          onClick={scrollToNextSection}>
            <ExpandCircleDownIcon style={{
              color: "inherit",
              fontSize: "inherit"
            }} />
          </WelcomeGoDownButton>
      </WelcomePageSegment>
      <WelcomePageSegment className="block-center">
        <WelcomeDescriptionHeader className="block-center">
          Who am I?
        </WelcomeDescriptionHeader>
        <WelcomeDescriptionContent className="block-center">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur nesciunt dicta corrupti officia itaque est adipisci ratione commodi illum et nemo facere cupiditate sapiente necessitatibus, fugit eveniet eum totam nisi.
        </WelcomeDescriptionContent>
        <WelcomeDescriptionContent className="block-center">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur nesciunt dicta corrupti officia itaque est adipisci ratione commodi illum et nemo facere cupiditate sapiente necessitatibus, fugit eveniet eum totam nisi.
        </WelcomeDescriptionContent>
      </WelcomePageSegment>
    </div>
  )
}
