import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import ExpandCircleDownIcon from '@mui/icons-material/ExpandCircleDown';
import { useMediaQuery } from '@mui/material';

import { WelcomeDescriptionContent, WelcomeDescriptionHeader, WelcomeGoDownButton, WelcomeHeader, WelcomePageSegment, WelcomeShortDescriptionWrapper } from 'styled/components/welcome/welcome'
import styles from '../styles/Home.module.css'

export default function Home() {

  const scrollButtonRef = React.createRef<HTMLButtonElement>();
  const scrollToNextSection = () => window.scrollBy(0, 90 * (window.innerHeight / 100));

  const isBiggerThanTablet:boolean = useMediaQuery("(min-width: 768px)");

  const descriptionContent:string[] = ["My name is Szymon Kupisz. I'm studying Computer Science and Information Systems at the Faculty of Mathematics and Information Sciences of the Warsaw University of Technology.",
    "I'm also a vice-president of the Student IT Research group of Warsaw University of Technology, which is KNI, and a president of it's flag product, the Sparkledge application."];

  return (
    <div>
      <Head>
        <title>Simon G. Kupisz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WelcomePageSegment className="block-center">
        <WelcomeHeader className="block-center" layout initial={{
            marginLeft: "100%",
          }} animate={{
            marginLeft: ["100%", "0%"]
          }} transition={{
            duration: 0.7,
            delay: 0.2
          }}>
            Welcome, my friend...
          </WelcomeHeader>
          <WelcomeShortDescriptionWrapper className="block-center" layout initial={{
            marginLeft: "-100%",
          }} animate={{
            marginLeft: ["-100%", "5%"]
          }} transition={{
            duration: 0.5,
            delay: 0.4
          }}>
            To the short and brief story of my career, of my skills, of who I am...
          </WelcomeShortDescriptionWrapper>
          <WelcomeGoDownButton type="button" className="block-center" layout initial={{
            scale: "0"
          }} animate={{
            scale: ["0","1"]
          }} transition={{
            duration: 0.4,
            delay: 0.9
          }} ref={scrollButtonRef}
          onClick={scrollToNextSection}>
            <ExpandCircleDownIcon style={{
              color: "inherit",
              fontSize: "inherit"
            }} />
          </WelcomeGoDownButton>
      </WelcomePageSegment>
      <WelcomePageSegment className="block-center">
        <WelcomeDescriptionHeader className="block-center">
          Who am I?
        </WelcomeDescriptionHeader>
        {isBiggerThanTablet ? <WelcomeDescriptionContent className="block-center">
          {`${descriptionContent[0]} ${descriptionContent[1]}`}
        </WelcomeDescriptionContent> : <>
            {descriptionContent.map((elem: string) => <WelcomeDescriptionContent className="block-center">
              {elem}
            </WelcomeDescriptionContent>)}
        </>}
        <WelcomeDescriptionContent className="block-center">
          Since I can remember, my life has been strongly bonded with programming. I started learning its concepts and wonders when I was 9 years old. Since that time, firstly with the help of my father, and then by myself, I've gone into the endless journey through the world of programming.
        </WelcomeDescriptionContent>
      </WelcomePageSegment>
    </div>
  )
}
