import Head from 'next/head'
import Image from 'next/image'
import { WelcomeHeader } from 'styled/components/welcome/welcome'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Simon G. Kupisz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <WelcomeHeader className="block-center" layout initial={{
          marginLeft: "100%",
        }} animate={{
          marginLeft: ["100%", "0%"]
        }} transition={{
          duration: 0.9,
          delay: 0.2
        }}>
          Welcome, my friend...
        </WelcomeHeader>
    </div>
  )
}
